### ISSUE TITLE
release into kinetic

### ISSUE THREAD

**Issue by rhaschke** [mikeferguson/grasping_msgs#1]
Could you please trigger the release into Kinetic? I have seen the package in shadow-fixed, but not yet in the official repo. Thanks.

**Comment by mikeferguson** [comment]
@rhaschke -- this was released on world moveit day -- it's building properly on the ROS buildfarm and is in ros-shadow-fixed, but there has not been a kinetic sync since then, which is why it is not yet in the main repo. I have no ability to trigger a sync -- that is an OSRF thing.

**Comment by rhaschke** [comment]
@mikeferguson There was a sync just recently. However, the package is still not there.
According to http://repositories.ros.org/status_page/ros_kinetic_default.html the package is not yet defined for the official release. I guess some action is required to have it in the release distribution.

**Comment by mikeferguson** [comment]
Package was released on August 23 (see https://github.com/ros/rosdistro/pull/12458).

Indigo & Jade got a public sync on August 25th, but Kinetic looks to not have been synced since 8/17 based on ros-users emails.

As I previously said, I cannot trigger a release -- please request one from OSRF (the usual channel is here: http://discourse.ros.org/c/release)
